### ISSUE TITLE
localhost:8000/txs/admin/login redirects to same login window after successful login

### ISSUE THREAD

**Issue by yod527** [safe-global/safe-infrastructure#39] opened 2022-07-19 12:44 UTC
Hi there!

I just tried to launch the local docker-compose version with pretty-much default settings.
After successful user creation via 
```
docker exec -ti safe-infrastructure_txs-web_1 python manage.py createsuperuser --username root
```
I can't log in with `localhost:8000/txs/admin` URL, with configured username/password, it just redirects me back to the same login window, without any error in docker logs, or on frontend, or in frontend-console.

BTW, localhost:8000/cfg/admin is working as expected.

Versions are:

CFG_VERSION=v2.23.0
CGW_VERSION=v3.26.0
TXS_VERSION=v4.4.2

Any ideas?
Thanks

**Comment by moisses89** [comment] 2022-07-19 16:55
Hi @yod527 reviewing the [documentation](https://github.com/safe-global/safe-infrastructure/blob/main/docs/running_locally.md) I think that your command is wrong because the container `safe-infrastructure_txs-web_1` doesn't exist in the compose file. 
Try this command to use interactive mode:
`docker exec -it safe-infrastructure-txs-web-1 python manage.py createsuperuser  --username root`

**Comment by yod527** [comment] 2022-07-20 07:26
@moisses89 it's just the way docker-compose names the containers in my case.. If I will refer to command in documentation, I will get "no such container" error. The user is created by the script without any issues. If I try to login without user creation or with wrong login credentials I will get `Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.` error. My settings are default, I've only specified some RPC_NODE_URL as it is written in documentation. I feel like issue is not in docker, or docker-compose, or me unable to launch a user-creation script. It's probably in some wrong configuration of the services or safe-transaction service itself. I will be happy to blame MacOS and Docker-desktop which I'm using, but on production ubuntu stand (where configuration are far away from default) I'm facing exactly the same issue, unfortunately.

**Comment by Uxio0** [comment] 2022-07-20 09:56
Hi @yod527 I cannot reproduce, just deleted everything with `docker compose down` and made sure everything is at the last version:

```
cp .env.sample .env
docker compose pull
docker compose up
```

I'm using `Docker 20.10.17` and `Docker Compose 2.6.1`

**Comment by yod527** [comment] 2022-07-20 10:23
@Uxio0 thanks for checking that for me, can I kindly ask to provide some test RPC_NODE_URL which you're using? Without setting of this var, the safe-infrastructure-txs-web-1 does not boot up. Maybe, the reason is in my roc node which I'm using..

**Comment by yod527** [comment] 2022-07-20 12:51
```
==> 12:29:09 ==> Collecting statics... 
==> 12:29:09 ==> Send via Slack info about service version and network
==> 12:29:09 ==> Running Gunicorn... 
[2022-07-20 12:29:10 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-07-20 12:29:10 +0000] [1] [INFO] Listening at: unix:/nginx/gunicorn.socket,http://0.0.0.0:8888 (1)
[2022-07-20 12:29:10 +0000] [1] [INFO] Using worker: gevent
[2022-07-20 12:29:10 +0000] [14] [INFO] Booting worker with pid: 14
[2022-07-20 12:29:10 +0000] [14] [INFO] Making Psycopg2 Green
[2022-07-20 12:29:10 +0000] [14] [INFO] Made Psycopg2 Green
Starting Safe Transaction Service version 4.4.2 on Matic
Slack not configured, ignoring
2022-07-20 12:29:16,976 [INFO] [MainProcess] DbTxDecoder: Loading contract ABIs for decoding
[2022-07-20 12:29:17 +0000] [14] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/site-packages/django_db_geventpool/backends/postgresql_psycopg2/base.py", line 49, in get_new_connection
    self.connection = self.pool.get()
  File "/usr/local/lib/python3.10/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 76, in get
    conn = self.create_connection()
  File "/usr/local/lib/python3.10/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 119, in create_connection
    conn = self.connect(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/usr/local/lib/python3.10/site-packages/psycogreen/gevent.py", line 32, in gevent_wait_callback
    state = conn.poll()
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "txs-db" (192.168.240.5) and accepting
        TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/wsgi.py", line 38, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/app/safe_transaction_service/history/apps.py", line 21, in ready
    get_db_tx_decoder()  # Build tx decoder cache
  File "/app/safe_transaction_service/contracts/tx_decoder.py", line 129, in get_db_tx_decoder
    return _get_db_tx_decoder()
  File "/app/safe_transaction_service/contracts/tx_decoder.py", line 122, in _get_db_tx_decoder
    return DbTxDecoder()
  File "/app/safe_transaction_service/contracts/tx_decoder.py", line 159, in __init__
    ] = self._generate_selectors_with_abis_from_abis(self.get_supported_abis())
  File "/app/safe_transaction_service/contracts/tx_decoder.py", line 232, in _generate_selectors_with_abis_from_abis
    return {
  File "/app/safe_transaction_service/contracts/tx_decoder.py", line 232, in <dictcomp>
    return {
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 353, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 171, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1130, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1171, in execute_sql
    cursor = self.connection.chunked_cursor()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 266, in chunked_cursor
    return self._cursor(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/site-packages/django_db_geventpool/backends/postgresql_psycopg2/base.py", line 49, in get_new_connection
    self.connection = self.pool.get()
  File "/usr/local/lib/python3.10/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 76, in get
    conn = self.create_connection()
  File "/usr/local/lib/python3.10/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 119, in create_connection
    conn = self.connect(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/usr/local/lib/python3.10/site-packages/psycogreen/gevent.py", line 32, in gevent_wait_callback
    state = conn.poll()
django.db.utils.OperationalError: could not connect to server: Connection refused
        Is the server running on host "txs-db" (192.168.240.5) and accepting
        TCP/IP connections on port 5432?

[2022-07-20 12:29:17 +0000] [14] [INFO] Worker exiting (pid: 14)
[2022-07-20 12:29:17 +0000] [1] [INFO] Shutting down: Master
[2022-07-20 12:29:17 +0000] [1] [INFO] Reason: Worker failed to boot.
==> 12:29:58 ==> Collecting statics... 
==> 12:29:58 ==> Send via Slack info about service version and network
==> 12:29:58 ==> Running Gunicorn... 
[2022-07-20 12:29:58 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-07-20 12:29:58 +0000] [1] [INFO] Listening at: unix:/nginx/gunicorn.socket,http://0.0.0.0:8888 (1)
[2022-07-20 12:29:58 +0000] [1] [INFO] Using worker: gevent
[2022-07-20 12:29:58 +0000] [15] [INFO] Booting worker with pid: 15
[2022-07-20 12:29:58 +0000] [15] [INFO] Making Psycopg2 Green
[2022-07-20 12:29:58 +0000] [15] [INFO] Made Psycopg2 Green
2022-07-20 12:30:03,316 [INFO] [MainProcess] DbTxDecoder: Loading contract ABIs for decoding
[2022-07-20 12:30:03 +0000] [15] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "contracts_contractabi" does not exist
LINE 1: ...OLD FOR SELECT "contracts_contractabi"."abi" FROM "contracts...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "contracts_contractabi" does not exist
LINE 1: ...OLD FOR SELECT "contracts_contractabi"."abi" FROM "contracts...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/wsgi.py", line 38, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/app/safe_transaction_service/history/apps.py", line 21, in ready
    get_db_tx_decoder()  # Build tx decoder cache
  File "/app/safe_transaction_service/contracts/tx_decoder.py", line 129, in get_db_tx_decoder
    return _get_db_tx_decoder()
  File "/app/safe_transaction_service/contracts/tx_decoder.py", line 122, in _get_db_tx_decoder
    return DbTxDecoder()
  File "/app/safe_transaction_service/contracts/tx_decoder.py", line 159, in __init__
    ] = self._generate_selectors_with_abis_from_abis(self.get_supported_abis())
  File "/app/safe_transaction_service/contracts/tx_decoder.py", line 232, in _generate_selectors_with_abis_from_abis
    return {
  File "/app/safe_transaction_service/contracts/tx_decoder.py", line 232, in <dictcomp>
    return {
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 353, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 171, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1130, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1178, in execute_sql
    cursor.close()
psycopg2.errors.InvalidCursorName: cursor "_django_curs_140598052287792_sync_1" does not exist

[2022-07-20 12:30:03 +0000] [15] [INFO] Worker exiting (pid: 15)
Starting Safe Transaction Service version 4.4.2 on Matic
Slack not configured, ignoring
[2022-07-20 12:30:04 +0000] [1] [INFO] Shutting down: Master
[2022-07-20 12:30:04 +0000] [1] [INFO] Reason: Worker failed to boot.
==> 12:30:22 ==> Collecting statics... 
==> 12:30:22 ==> Send via Slack info about service version and network
==> 12:30:22 ==> Running Gunicorn... 
[2022-07-20 12:30:23 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-07-20 12:30:23 +0000] [1] [INFO] Listening at: unix:/nginx/gunicorn.socket,http://0.0.0.0:8888 (1)
[2022-07-20 12:30:23 +0000] [1] [INFO] Using worker: gevent
[2022-07-20 12:30:23 +0000] [13] [INFO] Booting worker with pid: 13
[2022-07-20 12:30:23 +0000] [13] [INFO] Making Psycopg2 Green
[2022-07-20 12:30:23 +0000] [13] [INFO] Made Psycopg2 Green
2022-07-20 12:30:29,393 [INFO] [MainProcess] DbTxDecoder: Loading contract ABIs for decoding
2022-07-20 12:30:29,541 [INFO] [MainProcess] DbTxDecoder: Contract ABIs for decoding were loaded
Starting Safe Transaction Service version 4.4.2 on Matic
Slack not configured, ignoring
2022-07-20 12:32:06,842 MT::GET::admin/login/::1258::200::/txs/admin/login/
2022-07-20 12:32:08,918 MT::GET::admin/login/::16::200::/txs/admin/login/
2022-07-20 12:32:14,714 MT::POST::admin/login/::460::302::/txs/admin/login/
2022-07-20 12:32:14,740 MT::GET::admin/::2::302::/txs/admin/
2022-07-20 12:32:14,767 MT::GET::admin/login/::8::200::/txs/admin/login/
2022-07-20 12:32:23,711 MT::POST::admin/login/::259::302::/txs/admin/login/
2022-07-20 12:32:23,729 MT::GET::admin/::1::302::/txs/admin/
2022-07-20 12:32:23,751 MT::GET::admin/login/::7::200::/txs/admin/login/
```

@Uxio0 Unfortunately, same result for me with your .env file...
Here is the full log of  safe-infrastructure-txs-web-1 service, since the very beginning, in my case.

1st restart is due to postgresql container is created, but Postgres itself not booted yet. That's ok
2nd restart - I'm doing that manually, because of some migration errors (Potential issue?)

I've checked the database, after running the user creation script, root user with my email is present under auth_user table in Postgres database, so I assume create user script is running fine...

**Comment by Uxio0** [comment] 2022-07-20 12:56
Could you remove `data` folder?

**Comment by fmrsabino** [comment] 2022-07-20 12:57
> The user is created by the script without any issues. If I try to login without user creation or with wrong login credentials I will get `Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.` error.

Which browser are you using out of curiosity? I think this issue happened with one browser.
If you have another one could you try using that one? Just to check if this is the case.

**Comment by yod527** [comment] 2022-07-20 13:02
@fmrsabino that's the catch.

Chrome 103.0.5060.114 logs in without any issues.
Safari 15.5 (17613.2.7.1.8) - behaves like that.

My bad I haven't tried another browser, thank you guys for help!

**Comment by Uxio0** [comment] 2022-07-20 13:03
We are closing the issue as with Firefox and Chrome is working, and we don't intend to fix Safari. Though if someone provides a PR fixing it we will merge it

**Closed** 2022-07-20 13:03 UTC
